import {
  ErButton,
  ErButtonGroup,
  ErCollapse,
  ErCollapseItem,
  ErIcon,
  ErDropdown,
  ErDropdownItem,
  ErTooltip,
  ErMessage,
  ErSwitch,
  ErInput,
  ErSelect,
  ErOption,
  ErForm,
  ErFormItem,
  ErAlert,
  ErNotification,
  ErLoading,
  ErPopconfirm,
  ErMessageBox,
  ErConfigProvider
} from "@toy-element/components";
import type { Plugin } from "vue";

export default [
  ErButton,
  ErButtonGroup,
  ErCollapse,
  ErCollapseItem,
  ErIcon,
  ErDropdown,
  ErDropdownItem,
  ErTooltip,
  ErMessage,
  ErInput,
  ErSwitch,
  ErSelect,
  ErOption,
  ErForm,
  ErFormItem,
  ErAlert,
  ErNotification,
  ErLoading,
  ErPopconfirm,
  ErMessageBox,
  ErConfigProvider
] as Plugin[];
